import PaymentSection from "@/section/payment";
import Heading from "@/typography/heading";
import { Box, Container } from "@mui/material";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ background: "#12372A" }}>
        <Heading
          heading="Card payment"
          sx={{ color: "#FCFCFC", fontSize: "64px", fontWeight: 800 }}
        />
        <Heading
          heading="Checkout form"
          sx={{ color: "#FCFCFC", fontSize: "64px", fontWeight: 800 }}
        />
        <PaymentSection />
      </Box>
    </>
  );
}
